server:
  port: 8085
  context-path: /netshop

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1/netshop?characterEncoding=utf-8&useSSL=false
#    password: Xukai0110@
#    url: jdbc:mysql://106.14.183.207/netshop?characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource

  jpa:
    show-sql: true
    database: mysql

  jackson:
    default-property-inclusion: non_null

  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: utf-8
    content-type: text/html

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false

  mail:
    host: smtp.163.com
    username: xukai910110@163.com
    password: 10032460itachi
    default-encoding: UTF-8
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
        required: true
        ssl:
          enable: true

# 发送邮件地址
mail:
  sender: xukai910110@163.com

cookieConfig:
  buyerId: buyerId
  buyerName: buyerName
  sellerId: sellerId
  expire: 3600  #一小时

fdfs:
  so-timeout: 1500
  connect-timeout: 600
  thumb-image:
    width: 210
    height: 210
  tracker-list: 192.168.64.11:22122
  pool:
    jmx-enabled: false

baseUrl:
  frontBaseUrl: http://localhost:8081
  backBaseUrl: http://localhost:8085
  imageServerUrl: http://192.168.64.11/

crawler:
  proxySources: http://www.xicidaili.com/nn/
  proxySourcesMaxPage: 5
  proxyAddressQueueThreshold: 100
  proxyCrawlerWaitTime: 180000
#  proxyCrawlerWaitTime: 30000
  activeProxyListBaseThreshold: 20
  activeProxyListMaxThreshold: 50
  expressCrawlerBaseUrl: http://www.kuaidi100.com/query?type=|&postid=
  expressCrawlerWaitTime: 5000

autoAdmin:
  autoConfirmReceiveGoodsWaitTime: 10   #10天
  autoCancelNotPayedOrderWaitTime: 7200   #单位s，2小时
