server:
  port: 8085
  context-path: /netshop

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Xukai0110@
    url: jdbc:mysql://106.14.183.207/netshop?characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource

  jpa:
    show-sql: true
    database: mysql

  jackson:
    default-property-inclusion: non_null

  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: utf-8
    content-type: text/html

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false

cookieConfig:
  buyerId: buyerId
  buyerName: buyerName
  sellerId: sellerId
  expire: 3600  #一小时

fdfs:
  so-timeout: 1500
  connect-timeout: 600
  thumb-image:
    width: 210
    height: 210
  tracker-list: 106.14.183.207:22122
  pool:
    jmx-enabled: false

baseUrl:
  front_base_url: http://106.14.183.207:8081
  back_base_url: http://106.14.183.207:8085
  image_server_url: http://106.14.183.207/